stages:
  - build

build_linux:
  stage: build
  tags: [ubuntu]
  parallel:
    matrix:
      - c_compiler: gcc
        cxx_compiler: g++
        build_type: [Release, Debug]
      - c_compiler: clang
        cxx_compiler: clang++
        build_type: [Release, Debug]
  script:
    - |
      DEBIAN_FRONTEND=noninteractive

      sudo apt-get update
      sudo apt-get install -y git cmake build-essential libgl1-mesa-dev qt6-base-dev ninja-build clang doxygen

    - |
      cmake -B build -DCMAKE_BUILD_TYPE=$build_type -G Ninja -DCMAKE_C_COMPILER=$c_compiler -DCMAKE_CXX_COMPILER=$cxx_compiler .
      cmake --build build --config $build_type
