stages:
  - lint
  - build

build_linux: &build_linux
  stage: build
  tags: [ubuntu]
  parallel:
    matrix:
      - CC: gcc
        CXX: g++
        BUILD_TYPE: [Release, Debug]
      - CC: clang
        CXX: clang++
        BUILD_TYPE: [Release, Debug]
  script:
    - |
      DEBIAN_FRONTEND=noninteractive

      sudo --preserve-env=DEBIAN_FRONTEND apt-get update
      sudo --preserve-env=DEBIAN_FRONTEND apt-get install -y git cmake build-essential libgl1-mesa-dev qt6-base-dev ninja-build clang doxygen

    - .ci/build.sh
  when: always

build_linux_nix:
  <<: *build_linux
  script:
    - .ci/setup_nix.sh
    - |
      set -xeuo pipefail
      TMPDIR=$(mktemp -d)
      trap 'rm -rf "'"$TMPDIR"'"' EXIT
      nix develop -ic env XDG_CACHE_HOME=$TMPDIR CC=$CC CXX=$CXX BUILD_TYPE=$BUILD_TYPE .ci/build.sh

lint:
  stage: lint
  tags: [ubuntu]
  script:
    - .ci/setup_nix.sh
    - nix develop -ic .ci/lint.sh
