stages:
  - lint
  - build

build_linux:
  stage: build
  tags: [ubuntu]
  parallel:
    matrix:
      - CC: gcc
        CXX: g++
        BUILD_TYPE: [Release, Debug]
      - CC: clang
        CXX: clang++
        BUILD_TYPE: [Release, Debug]
  script:
    - |
      DEBIAN_FRONTEND=noninteractive

      sudo --preserve-env=DEBIAN_FRONTEND apt-get update
      sudo --preserve-env=DEBIAN_FRONTEND apt-get install -y git cmake build-essential libgl1-mesa-dev qt6-base-dev ninja-build clang doxygen

    - .ci/build.sh

lint:
  stage: lint
  tags: [ubuntu]
  script:
    - .ci/setup_nix.sh
    - nix develop -ic .ci/lint.sh
